
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.workshop': 'AI Workshop',
    'nav.signal_bridge': 'Signal Bridge',
    'nav.my_strategies': 'My Strategies',
    'nav.data_center': 'Data Center',
    'nav.community': 'Community',
    'nav.research': 'Research AI',
    'nav.live_setup': 'Live Setup',
    'nav.qmt_terminal': 'QMT Terminal',
    'nav.upgrade_pro': 'Upgrade Pro',
    'nav.profile': 'Profile',
    'nav.admin_dashboard': 'Admin Dashboard',

    // Theme & Lang
    'lang.en': 'English',
    'lang.zh': 'Chinese',

    // Landing
    'landing.status': 'System Status: V2.0 Stable Live',
    'landing.hero_title_1': 'Institutional Alpha,',
    'landing.hero_title_2': 'Democratized by AI.',
    'landing.hero_desc': 'The first quantitative ecosystem driven by Large Language Models. Generate institutional-grade Python strategies from natural language or mirror top-performing portfolios across the web instantly.',
    'landing.btn_start': 'Start Building Free',
    'landing.btn_docs': 'View API Docs',
    'landing.btn_launch': 'Launch Terminal',
    'landing.nav_platform': 'Platform',
    'landing.nav_engine': 'AI Engine',
    'landing.nav_bridge': 'Signal Bridge',
    'landing.nav_data': 'Data',
    'landing.core_engines': 'Core Engines',
    'landing.core_desc': 'Powered by dual engines for creation and replication.',
    'landing.feat_gen_title': 'Generative Code Engine',
    'landing.feat_gen_desc': 'Describe your logic in plain English. Our fine-tuned LLMs generate production-ready Python (Backtrader/QMT) code instantly with 0 syntax errors.',
    'landing.feat_bridge_title': 'Universal Signal Bridge',
    'landing.feat_bridge_desc': 'Break the walled gardens. Paste a URL from Snowball, JoinQuant, or iFind, and mirror trades in real-time with sub-millisecond latency.',
    'landing.feat_risk_title': 'Institutional Risk Control',
    'landing.feat_risk_desc': 'Built-in PIT (Point-in-Time) data cleaning, slippage protection, and automated rebalancing. We protect your capital before it enters the market.',
    'landing.data_title': 'Full-Stack Data Center',
    'landing.data_desc': 'Access clean, adjusted historical data and real-time streams for global markets.',
    'landing.data_btn': 'Explore Data Center',
    'landing.footer_rights': '© 2024 Quant AI Inc. Institutional Edition.',
    'landing.login': 'Log In',
    'landing.signup': 'Sign Up',
    'landing.demo_url_ph': 'Paste URL (e.g. Snowball/JoinQuant)',
    'landing.demo_parse': 'Parse Strategy',
    'landing.demo_analyzing': 'Analyzing...',
    'landing.demo_acquired': 'Signal Acquired',
    'landing.demo_result_return': 'Total Return',
    'landing.demo_cta_login': 'Log In to Mirror',

    // Auth
    'auth.login_title': 'Welcome Back',
    'auth.login_desc': 'Sign in to access your trading console',
    'auth.register_title': 'Create Account',
    'auth.register_desc': 'Start your journey to institutional alpha',
    'auth.email': 'Username / Email',
    'auth.phone': 'Phone Number',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.fullname': 'Full Name',
    'auth.remember': 'Remember me',
    'auth.forgot': 'Forgot password?',
    'auth.signin': 'Sign In',
    'auth.signup': 'Create Account',
    'auth.have_account': 'Already have an account?',
    'auth.no_account': "Don't have an account?",
    'auth.terms': 'I agree to the Terms of Service and Privacy Policy',
    'auth.or_continue': 'Or continue with',
    'auth.tab_account': 'Account Login',
    'auth.tab_phone': 'Phone Login',
    'auth.tab_wechat': 'WeChat',
    'auth.captcha': 'Captcha',
    'auth.sms_code': 'SMS Code',
    'auth.get_code': 'Get Code',
    'auth.resend': 'Resend',
    'auth.scan_wechat': 'Scan with WeChat',
    'auth.bind_wechat_title': 'Bind WeChat',
    'auth.bind_wechat_desc': 'Link your WeChat account for instant login and trade notifications.',
    'auth.skip': 'Skip for now',
    'auth.bind': 'Bind Now',

    // Dashboard
    'dash.hero_title': 'Build Institutional-Grade',
    'dash.hero_title_highlight': 'Alpha with AI',
    'dash.hero_desc': 'Eliminate technical barriers. Use natural language to generate robust trading strategies or instantly mirror top-performing portfolios from external platforms.',
    'dash.btn_generate': 'Generate Strategy',
    'dash.btn_copy': 'Start Copy Trading',
    'dash.stat_vol': 'Total Trading Vol',
    'dash.stat_vol_sub': 'Platform wide real-time volume',
    'dash.stat_active': 'Active Strategies',
    'dash.stat_active_sub': 'Running across QMT & Ptrade',
    'dash.stat_apy': 'Top APY Today',
    'dash.stat_apy_sub': "Strategy: 'Alpha-Dragon-V2'",
    'dash.market_sentiment': 'Market Sentiment',
    'dash.recent_signals': 'Recent Community Signals',

    // Workshop
    'work.title': 'AI Assistant',
    'work.model_select': 'Model',
    'work.empty_state': 'Describe your strategy idea, or choose a template above.',
    'work.empty_hint': 'e.g., "Buy Apple when RSI is below 30 and sell when above 70"',
    'work.input_placeholder': 'Input strategy logic...',
    'work.code_title': 'Code Editor',
    'work.btn_format': 'Format',
    'work.code_placeholder': '# AI generated code will appear here...',
    'work.backtest_title': 'Backtest Configuration',
    'work.ready_test': 'Ready to test',
    'work.sharpe': 'Sharpe Ratio',
    'work.max_dd': 'Max Drawdown',
    'work.btn_run': 'Run Backtest',
    'work.btn_running': 'Running Simulation...',
    'work.date_start': 'Start Date',
    'work.date_end': 'End Date',
    'work.strat_name_ph': 'Strategy Name (e.g. Mean Reversion V1)',
    'work.btn_save': 'Save to Library',
    'work.save_success': 'Strategy saved to My Library',
    'work.save_error': 'Please provide a name and code',
    'work.templates': 'Strategy Templates',
    'work.tpl_ma_name': 'Double MA Trend',
    'work.tpl_ma_desc': 'Classic Golden Cross strategy using SMA(5) and SMA(20).',
    'work.tpl_rsi_name': 'RSI Reversion',
    'work.tpl_rsi_desc': 'Buy when RSI < 30, Sell when RSI > 70.',
    'work.tpl_grid_name': 'Spot Grid',
    'work.tpl_grid_desc': 'Automated buy low sell high within a specific price range.',
    'work.tpl_smallcap_name': 'Small Cap Rotation',
    'work.tpl_smallcap_desc': 'Buy bottom 10% market cap stocks, rebalance monthly.',
    'work.btn_load': 'Load',

    // Signal Bridge
    'bridge.title': 'Universal Signal Bridge',
    'bridge.desc': 'Connect external portfolio URLs to automate signal copying.',
    'bridge.input_placeholder': 'Paste URL (e.g., https://xueqiu.com/P/ZH123456)',
    'bridge.btn_connect': 'Connect',
    'bridge.btn_analyzing': 'Parsing...',
    'bridge.btn_connected': 'Connected',
    'bridge.status_waiting': 'Waiting for signal source...',
    'bridge.status_crawling': 'Crawling portfolio data...',
    'bridge.risk_title': 'Risk Management',
    'bridge.risk_multiplier': 'Copy Multiplier',
    'bridge.risk_reverse': 'Reverse Copy (Short)',
    'bridge.risk_slippage': 'Slippage protection enabled. Orders > 2% deviation will be rejected.',
    'bridge.stream_title': 'Live Signal Stream',

    // My Strategies
    'mystrat.title': 'My Strategies',
    'mystrat.tab_live': 'Live Strategies',
    'mystrat.tab_lib': 'My Strategy Library',
    'mystrat.assets': 'Total Assets',
    'mystrat.day_pnl': 'Day P&L',
    'mystrat.active_count': 'Active Strategies',
    'mystrat.edit_modal': 'Strategy Details',
    'mystrat.btn_save': 'Save Changes',
    'mystrat.btn_pause': 'Pause Strategy',
    'mystrat.btn_start': 'Start Strategy',
    'mystrat.roi': 'ROI',
    'mystrat.maxdd': 'Max Drawdown',
    'mystrat.win_rate': 'Win Rate',
    'mystrat.code_preview': 'Source Code',
    'mystrat.strat_name': 'Strategy Name',
    'mystrat.strat_desc': 'Description',
    'mystrat.empty_live': 'No strategies are currently running live.',
    'mystrat.empty_lib': 'Your library is empty. Create one in AI Workshop or clone from Community.',

    // Data Center
    'data.title': 'Data Center',
    'data.tab_all': 'All Datasets',
    'data.tab_stock': 'Stocks',
    'data.tab_crypto': 'Crypto',
    'data.tab_macro': 'Macro',
    'data.tab_deriv': 'Derivatives',
    'data.sample': 'Sample Data',
    'data.api': 'API Access',
    'data.btn_copy_token': 'Copy Token',
    'data.status_active': 'Active',
    'data.status_subscribe': 'Subscribe',
    'data.price_free': 'Free',
    'data.price_pro': 'Pro',
    'data.btn_download': 'Download CSV',

    // Community
    'comm.title': 'Alpha Community',
    'comm.tab_feed': 'Feed',
    'comm.tab_market': 'Strategy Market',
    'comm.btn_post': 'New Post',
    'comm.reply': 'Reply',
    'comm.comments': 'Comments',
    'comm.post_create_title': 'Create New Post',
    'comm.post_title_ph': 'Enter post title...',
    'comm.post_content_ph': 'Share your strategy or market insights...',
    'comm.btn_publish': 'Publish Post',
    'comm.back': 'Back to Feed',
    'comm.official': 'OFFICIAL',
    'comm.subscribe': 'Subscribe',
    'comm.total_return': 'Total Return',
    'comm.btn_add_image': 'Add Image',
    'comm.btn_add_code': 'Add Code',
    'comm.search_ph': 'Search posts...',
    'comm.sort_views': 'Most Viewed',
    'comm.sort_latest_reply': 'Latest Reply',
    'comm.sort_newest': 'Newest',
    'comm.sort_likes': 'Most Liked',
    'comm.page_prev': 'Previous',
    'comm.page_next': 'Next',
    'comm.page_info': 'Page {curr} of {total}',

    // Profile & Settings
    'profile.title': 'Account Settings',
    'profile.edit_btn': 'Edit Profile',
    'profile.save_btn': 'Save Profile',
    'profile.cancel_btn': 'Cancel',
    'profile.change_pwd': 'Change Password',
    'profile.plan': 'Current Plan',
    'profile.api_key': 'AI Model Configuration',
    'profile.api_desc': 'Configure your API keys for different AI providers to power the Strategy Workshop.',
    'profile.notifications': 'Notification Settings',
    'profile.wechat_status': 'WeChat Binding',
    'profile.btn_regenerate': 'Update Key',
    'profile.btn_bind': 'Bind WeChat',
    'profile.btn_upgrade': 'Upgrade Plan',
    'profile.provider': 'Select Model Provider',
    'profile.key_ph': 'Enter API Key (sk-...)',
    'profile.save_key': 'Save Configuration',
    'profile.email_alerts': 'Email Alerts',
    'profile.email_desc': 'Daily digest and risk alerts',
    'profile.bound': 'Connected',
    'profile.not_bound': 'Not Connected',
    'profile.pwd_current': 'Current Password',
    'profile.pwd_new': 'New Password',
    'profile.pwd_confirm': 'Confirm Password',
    
    // Membership & Points
    'mem.tier_free': 'Free Member',
    'mem.tier_gold': 'Gold Member',
    'mem.tier_diamond': 'Diamond Member',
    'mem.points_balance': 'Points Balance',
    'mem.daily_limit': 'Daily Clone Limit',
    'mem.ben_clone_5': '5 Free Clones / Day',
    'mem.ben_clone_20': '20 Free Clones / Day',
    'mem.ben_ai_basic': 'Basic AI Usage',
    'mem.ben_ai_adv': 'Advanced AI Models',
    'mem.ben_support': 'Priority Support',
    'mem.btn_recharge': 'Recharge',
    'mem.btn_upgrade_gold': 'Upgrade to Gold',
    'mem.btn_upgrade_diamond': 'Upgrade to Diamond',
    'mem.pts_shop': 'Points Shop',
    'mem.pay_title': 'Secure Payment',
    'mem.pay_desc': 'Scan QR code to complete purchase',
    'mem.pay_wechat': 'WeChat Pay',
    'mem.pay_alipay': 'Alipay',
    'mem.pay_confirm': 'I have paid',
    'mem.price_mo': '/ month',
    
    // Membership Comparison
    'mem.modal_title': 'Membership Plans',
    'mem.feature_gen': 'Strategy Generation',
    'mem.feature_backtest': 'Backtest Runs',
    'mem.feature_clone': 'Signal Clone Limit',
    'mem.feature_ai': 'AI Models',
    'mem.feature_support': 'Support',
    'mem.free_price': 'Free',
    'mem.gold_price': '¥99 / mo',
    'mem.diamond_price': '¥199 / mo',
    'mem.current_plan': 'Current Plan',
    'mem.upgrade_now': 'Upgrade Now',

    // Research
    'research.title': 'Research Analysis',
    'research.upload_btn': 'Upload Report',
    'research.library': 'Report Library',
    'research.ai_analysis': 'AI Interpretation',
    'research.analyze_btn': 'Start AI Analysis',
    'research.analyzing': 'AI is analyzing...',
    'research.key_takeaways': 'Key Takeaways',
    'research.sentiment': 'Sentiment',
    'research.sentiment_bullish': 'Bullish',
    'research.sentiment_bearish': 'Bearish',
    'research.sentiment_neutral': 'Neutral',
    'research.sector': 'Sector',
    'research.analyst': 'Analyst',
    'research.date': 'Date',
    'research.sort_newest': 'Newest',
    'research.sort_hottest': 'Hottest',
    'research.filter_sector': 'Sector',
    'research.filter_tags': 'Tags',
    'research.filter_all': 'All',
    'research.factor_mining': 'AI Factor Mining',
    'research.btn_mine': 'Mine Factors',
    'research.mining': 'Mining Factors from Report...',
    'research.mined_factors': 'Mined Factors',
    'research.select_factors_desc': 'Select factors to generate a strategy.',
    'research.generate_strat': 'Generate Strategy',

    // Live Setup
    'live.title': 'Live Trading Environment',
    'live.list_title': 'Live Instances',
    'live.btn_add': 'New Instance',
    'live.btn_edit': 'Edit',
    'live.btn_save': 'Save Configuration',
    'live.btn_cancel': 'Cancel',
    'live.config': 'Container Configuration',
    'live.provider': 'Cloud Provider',
    'live.host': 'Host IP / Domain',
    'live.port': 'Port',
    'live.token': 'Auth Token',
    'live.broker': 'Broker Client',
    'live.account': 'Account ID',
    'live.btn_test': 'Test Connection',
    'live.btn_connect': 'Connect Container',
    'live.status': 'Connection Status',
    'live.terminal': 'Remote Terminal',
    'live.logs': 'Docker Logs',
    'live.push_strat': 'Push Strategies',
    'live.status_idle': 'Idle',
    'live.status_connecting': 'Connecting...',
    'live.status_connected': 'Online',
    'live.status_error': 'Error',
    'live.topology': 'Network Topology',
    'live.empty': 'No active instances. Click "New Instance" to connect a docker container.',
    
    // Admin & Roles
    'role.switch_to_admin': 'Switch to Admin',
    'role.switch_to_user': 'Switch to User',
    'role.current': 'Current Role',
    'admin.total_users': 'Total Users',
    'admin.total_revenue': 'Total Revenue',
    'admin.active_instances': 'Active Instances',
    'admin.system_health': 'System Health',
    'admin.recent_activity': 'Recent Activity',
    'admin.user_mgmt': 'Users',
    'admin.sys_config': 'System',
    'admin.content_audit': 'Content Audit',
    'admin.tab_overview': 'Overview',
    'admin.tab_users': 'User Management',
    'admin.tab_content': 'Content Mgmt',
    'admin.tab_system': 'System Logs',
    'admin.audit_pending': 'Pending Review',
    'admin.audit_approve': 'Approve',
    'admin.audit_reject': 'Reject',
    'admin.research_upload': 'Upload Research Report',
    'admin.strategy_audit': 'Strategy Audit',
    'admin.research_mgmt': 'Research Mgmt',
    'admin.log_stream': 'Real-time System Logs',
  },
  zh: {
    // Nav
    'nav.dashboard': '首页',
    'nav.workshop': 'AI 策略工坊',
    'nav.signal_bridge': '全网跟单',
    'nav.my_strategies': '我的策略',
    'nav.data_center': '全栈数据',
    'nav.community': '社区',
    'nav.research': '研报分析',
    'nav.live_setup': '实盘配置',
    'nav.qmt_terminal': 'QMT 实盘终端',
    'nav.upgrade_pro': '升级专业版',
    'nav.profile': '个人中心',
    'nav.admin_dashboard': '管理后台',

    // Theme & Lang
    'lang.en': 'English',
    'lang.zh': '简体中文',

    // Landing
    'landing.status': '系统状态: V2.0 稳定运行中',
    'landing.hero_title_1': '机构级 Alpha，',
    'landing.hero_title_2': '由 AI 普及大众。',
    'landing.hero_desc': '首个由大语言模型驱动的量化生态系统。通过自然语言生成机构级 Python 策略，或一键镜像全网顶尖投资组合。',
    'landing.btn_start': '免费构建策略',
    'landing.btn_docs': '查看 API 文档',
    'landing.btn_launch': '启动终端',
    'landing.nav_platform': '平台',
    'landing.nav_engine': 'AI 引擎',
    'landing.nav_bridge': '全网跟单',
    'landing.nav_data': '数据中心',
    'landing.core_engines': '双核引擎',
    'landing.core_desc': '创新双引擎驱动：AI 生产与全网复制。',
    'landing.feat_gen_title': '生成式代码引擎',
    'landing.feat_gen_desc': '用自然语言描述逻辑。微调大模型即刻生成无语法错误的生产级 Python (Backtrader/QMT) 代码。',
    'landing.feat_bridge_title': '全网跟单引擎',
    'landing.feat_bridge_desc': '打破生态孤岛。粘贴雪球、聚宽或同花顺的组合 URL，实现毫秒级实盘信号同步。',
    'landing.feat_risk_title': '机构级风控系统',
    'landing.feat_risk_desc': '内置 PIT (Point-in-Time) 数据清洗、滑点保护与自动再平衡。资金入场前，风控先行。',
    'landing.data_title': '全栈数据中心',
    'landing.data_desc': '访问经过清洗的全球市场历史数据与实时流。',
    'landing.data_btn': '探索数据中心',
    'landing.footer_rights': '© 2024 Quant AI Inc. 机构版',
    'landing.login': '登录',
    'landing.signup': '注册',
    'landing.demo_url_ph': '粘贴 URL (如: 雪球/聚宽组合)',
    'landing.demo_parse': '解析策略',
    'landing.demo_analyzing': '分析中...',
    'landing.demo_acquired': '信号已捕获',
    'landing.demo_result_return': '累计收益',
    'landing.demo_cta_login': '登录以开始跟单',

    // Auth
    'auth.login_title': '欢迎回来',
    'auth.login_desc': '登录以访问您的量化控制台',
    'auth.register_title': '创建账户',
    'auth.register_desc': '开启您的机构级量化之旅',
    'auth.email': '账号/邮箱',
    'auth.phone': '手机号码',
    'auth.password': '密码',
    'auth.confirm_password': '确认密码',
    'auth.fullname': '真实姓名',
    'auth.remember': '记住我',
    'auth.forgot': '忘记密码？',
    'auth.signin': '登录',
    'auth.signup': '立即注册',
    'auth.have_account': '已有账户？',
    'auth.no_account': "还没有账户？",
    'auth.terms': '我同意服务条款和隐私政策',
    'auth.or_continue': '或通过以下方式继续',
    'auth.tab_account': '账号登录',
    'auth.tab_phone': '手机登录',
    'auth.tab_wechat': '微信扫码',
    'auth.captcha': '图形验证码',
    'auth.sms_code': '短信验证码',
    'auth.get_code': '获取验证码',
    'auth.resend': '重发',
    'auth.scan_wechat': '使用微信扫一扫登录',
    'auth.bind_wechat_title': '绑定微信',
    'auth.bind_wechat_desc': '绑定微信账号，即可享受微信扫码登录及实时交易成交推送通知。',
    'auth.skip': '暂不绑定',
    'auth.bind': '立即绑定',

    // Dashboard
    'dash.hero_title': '以自然语言，构建',
    'dash.hero_title_highlight': '机构级 Alpha',
    'dash.hero_desc': '消除技术壁垒。使用自然语言构建稳健的交易策略，或即刻镜像外部平台的顶尖投资组合。',
    'dash.btn_generate': '立即生成策略',
    'dash.btn_copy': '开启一键跟单',
    'dash.stat_vol': '平台总交易额',
    'dash.stat_vol_sub': '全平台实时成交量',
    'dash.stat_active': '运行中策略',
    'dash.stat_active_sub': '跨 QMT & Ptrade 终端',
    'dash.stat_apy': '今日最高收益',
    'dash.stat_apy_sub': "策略: 'Alpha-Dragon-V2'",
    'dash.market_sentiment': '市场情绪',
    'dash.recent_signals': '社区最新信号',

    // Workshop
    'work.title': 'AI 助手',
    'work.model_select': '模型',
    'work.empty_state': '描述您的策略思路，或者点击上方模板快速开始。',
    'work.empty_hint': '例如："当 RSI 低于 30 时买入苹果，高于 70 时卖出"',
    'work.input_placeholder': '输入策略逻辑...',
    'work.code_title': '代码编辑器',
    'work.btn_format': '格式化',
    'work.code_placeholder': '# AI 生成的代码将显示在这里...',
    'work.backtest_title': '回测配置',
    'work.ready_test': '准备就绪',
    'work.sharpe': '夏普比率',
    'work.max_dd': '最大回撤',
    'work.btn_run': '运行回测',
    'work.btn_running': '回测运行中...',
    'work.date_start': '开始日期',
    'work.date_end': '结束日期',
    'work.strat_name_ph': '策略名称 (如: 均值回归 V1)',
    'work.btn_save': '保存到策略库',
    'work.save_success': '策略已保存',
    'work.save_error': '请提供策略名称和代码',
    'work.templates': '策略模板库',
    'work.tpl_ma_name': '双均线趋势',
    'work.tpl_ma_desc': '经典的金叉/死叉策略 (SMA5/SMA20)。',
    'work.tpl_rsi_name': 'RSI 均值回归',
    'work.tpl_rsi_desc': 'RSI < 30 买入, RSI > 70 卖出。',
    'work.tpl_grid_name': '现货网格',
    'work.tpl_grid_desc': '在特定价格区间内自动高抛低吸。',
    'work.tpl_smallcap_name': '小市值轮动',
    'work.tpl_smallcap_desc': '买入市值最小的 10% 股票，按月调仓。',
    'work.btn_load': '加载模板',

    // Signal Bridge
    'bridge.title': '全网跟单引擎',
    'bridge.desc': '连接外部投资组合 URL，自动同步交易信号。',
    'bridge.input_placeholder': '粘贴组合链接 (如: https://xueqiu.com/P/ZH123456)',
    'bridge.btn_connect': '开始连接',
    'bridge.btn_analyzing': '解析中...',
    'bridge.btn_connected': '已连接',
    'bridge.status_waiting': '等待信号源接入...',
    'bridge.status_crawling': '正在爬取持仓数据...',
    'bridge.risk_title': '跟单风控配置',
    'bridge.risk_multiplier': '跟单倍率',
    'bridge.risk_reverse': '反向跟单 (做空)',
    'bridge.risk_slippage': '滑点保护已开启。偏离度 > 2% 的信号将被拒绝。',
    'bridge.stream_title': '实时信号流',

    // My Strategies
    'mystrat.title': '我的策略',
    'mystrat.tab_live': '实盘运行',
    'mystrat.tab_lib': '我的策略库',
    'mystrat.assets': '总资产净值',
    'mystrat.day_pnl': '今日盈亏',
    'mystrat.active_count': '运行中策略',
    'mystrat.edit_modal': '策略详情',
    'mystrat.btn_save': '保存修改',
    'mystrat.btn_pause': '暂停策略',
    'mystrat.btn_start': '启动策略',
    'mystrat.roi': '累计收益率',
    'mystrat.maxdd': '最大回撤',
    'mystrat.win_rate': '胜率',
    'mystrat.code_preview': '策略源代码',
    'mystrat.strat_name': '策略名称',
    'mystrat.strat_desc': '策略描述',
    'mystrat.empty_live': '当前没有正在实盘运行的策略。',
    'mystrat.empty_lib': '策略库为空。请在 AI 工坊创建或从社区克隆。',

    // Data Center
    'data.title': '全栈数据中心',
    'data.tab_all': '全部数据',
    'data.tab_stock': '股票',
    'data.tab_crypto': '数字货币',
    'data.tab_macro': '宏观经济',
    'data.tab_deriv': '衍生品',
    'data.sample': '数据样例',
    'data.api': 'API 接入',
    'data.btn_copy_token': '复制 Token',
    'data.status_active': '已接入',
    'data.status_subscribe': '订阅',
    'data.price_free': '免费',
    'data.price_pro': '专业版',
    'data.btn_download': '下载 CSV',

    // Community
    'comm.title': 'Alpha 社区',
    'comm.tab_feed': '最新动态',
    'comm.tab_market': '策略集市',
    'comm.btn_post': '发布帖子',
    'comm.reply': '回复',
    'comm.comments': '条评论',
    'comm.post_create_title': '发布新内容',
    'comm.post_title_ph': '输入标题...',
    'comm.post_content_ph': '分享您的策略逻辑或市场观点...',
    'comm.btn_publish': '立即发布',
    'comm.back': '返回列表',
    'comm.official': '官方',
    'comm.subscribe': '订阅策略',
    'comm.total_return': '累计回报',
    'comm.btn_add_image': '插入图片',
    'comm.btn_add_code': '插入代码',
    'comm.search_ph': '搜索帖子...',
    'comm.sort_views': '浏览量',
    'comm.sort_latest_reply': '最新回复',
    'comm.sort_newest': '最新发布',
    'comm.sort_likes': '点赞数',
    'comm.page_prev': '上一页',
    'comm.page_next': '下一页',
    'comm.page_info': '第 {curr} 页 / 共 {total} 页',

    // Profile & Settings
    'profile.title': '账户设置',
    'profile.edit_btn': '编辑资料',
    'profile.save_btn': '保存资料',
    'profile.cancel_btn': '取消',
    'profile.change_pwd': '修改密码',
    'profile.plan': '当前套餐',
    'profile.api_key': 'AI 模型配置',
    'profile.api_desc': '配置您的 API Key 以启用 AI 策略生成功能。支持多厂商模型接入。',
    'profile.notifications': '通知设置',
    'profile.wechat_status': '微信绑定状态',
    'profile.btn_regenerate': '更新密钥',
    'profile.btn_bind': '绑定微信',
    'profile.btn_upgrade': '升级套餐',
    'profile.provider': '选择模型厂商',
    'profile.key_ph': '输入 API Key (sk-...)',
    'profile.save_key': '保存配置',
    'profile.email_alerts': '邮件日报',
    'profile.email_desc': '每日发送交易摘要与风控警报',
    'profile.bound': '已绑定',
    'profile.not_bound': '未绑定',
    'profile.pwd_current': '当前密码',
    'profile.pwd_new': '新密码',
    'profile.pwd_confirm': '确认新密码',
    
    // Membership & Points
    'mem.tier_free': '普通用户',
    'mem.tier_gold': '黄金会员',
    'mem.tier_diamond': '钻石会员',
    'mem.points_balance': '积分余额',
    'mem.daily_limit': '今日克隆额度',
    'mem.ben_clone_5': '每日 5 次免费克隆',
    'mem.ben_clone_20': '每日 20 次免费克隆',
    'mem.ben_ai_basic': '基础 AI 模型使用',
    'mem.ben_ai_adv': '高级 AI 模型 (DeepSeek)',
    'mem.ben_support': '专属客服支持',
    'mem.btn_recharge': '充值积分',
    'mem.btn_upgrade_gold': '升级黄金会员',
    'mem.btn_upgrade_diamond': '升级钻石会员',
    'mem.pts_shop': '积分商城',
    'mem.pay_title': '安全支付',
    'mem.pay_desc': '请扫描二维码完成支付',
    'mem.pay_wechat': '微信支付',
    'mem.pay_alipay': '支付宝',
    'mem.pay_confirm': '我已支付',
    'mem.price_mo': '/ 月',
    
    // Membership Comparison
    'mem.modal_title': '会员权益对比',
    'mem.feature_gen': '策略生成',
    'mem.feature_backtest': '回测次数',
    'mem.feature_clone': '跟单/克隆限制',
    'mem.feature_ai': 'AI 模型支持',
    'mem.feature_support': '技术支持',
    'mem.free_price': '免费',
    'mem.gold_price': '¥99 / 月',
    'mem.diamond_price': '¥199 / 月',
    'mem.current_plan': '当前方案',
    'mem.upgrade_now': '立即升级',

    // Research
    'research.title': '研报智能分析',
    'research.upload_btn': '上传研报',
    'research.library': '研报库',
    'research.ai_analysis': 'AI 深度解读',
    'research.analyze_btn': '开始分析',
    'research.analyzing': 'AI 正在分析中...',
    'research.key_takeaways': '核心观点',
    'research.sentiment': '市场情绪倾向',
    'research.sentiment_bullish': '看多 (Bullish)',
    'research.sentiment_bearish': '看空 (Bearish)',
    'research.sentiment_neutral': '中性 (Neutral)',
    'research.sector': '行业板块',
    'research.analyst': '分析师/机构',
    'research.date': '发布日期',
    'research.sort_newest': '最新发布',
    'research.sort_hottest': '热度最高',
    'research.filter_sector': '板块筛选',
    'research.filter_tags': '标签筛选',
    'research.filter_all': '全部',
    'research.factor_mining': 'AI 因子挖掘',
    'research.btn_mine': '挖掘因子',
    'research.mining': '正在从研报中挖掘潜在因子...',
    'research.mined_factors': '已挖掘因子',
    'research.select_factors_desc': '选择因子以生成 AI 策略。',
    'research.generate_strat': '生成策略',

    // Live Setup
    'live.title': '实盘环境配置',
    'live.list_title': '实盘实例列表',
    'live.btn_add': '新增实盘实例',
    'live.btn_edit': '编辑',
    'live.btn_save': '保存配置',
    'live.btn_cancel': '返回列表',
    'live.config': '容器连接配置',
    'live.provider': '云服务商',
    'live.host': '主机 IP / 域名',
    'live.port': '端口',
    'live.token': '认证 Token',
    'live.broker': '券商柜台客户端',
    'live.account': '资金账号',
    'live.btn_test': '测试连接',
    'live.btn_connect': '连接容器',
    'live.status': '连接状态',
    'live.terminal': '远程日志终端',
    'live.logs': 'Docker 运行日志',
    'live.push_strat': '推送策略到实盘',
    'live.status_idle': '空闲',
    'live.status_connecting': '正在连接...',
    'live.status_connected': '在线',
    'live.status_error': '连接错误',
    'live.topology': '网络拓扑状态',
    'live.empty': '暂无活跃实例。请点击“新增实盘实例”连接 Docker 容器。',
    
    // Admin & Roles
    'role.switch_to_admin': '切换至管理员',
    'role.switch_to_user': '切换至用户视图',
    'role.current': '当前角色',
    'admin.total_users': '总用户数',
    'admin.total_revenue': '总营收',
    'admin.active_instances': '活跃实盘',
    'admin.system_health': '系统健康度',
    'admin.recent_activity': '近期活动日志',
    'admin.user_mgmt': '用户管理',
    'admin.sys_config': '系统配置',
    'admin.content_audit': '内容审核',
    'admin.tab_overview': '概览',
    'admin.tab_users': '用户管理',
    'admin.tab_content': '内容管理',
    'admin.tab_system': '系统监控',
    'admin.audit_pending': '待审核',
    'admin.audit_approve': '通过',
    'admin.audit_reject': '拒绝',
    'admin.research_upload': '上传研报',
    'admin.strategy_audit': '策略审核',
    'admin.research_mgmt': '研报管理',
    'admin.log_stream': '实时系统日志',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh'); 

  useEffect(() => {
    const browserLang = navigator.language;
    if (browserLang.startsWith('zh')) {
      setLanguage('zh');
    } else {
      setLanguage('en');
    }
  }, []);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
